server:
  servlet:
    context-path: "/api"

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
    hibernate:
      ddl-auto: create-drop
    database: mysql

springdoc:
  version: 'v1'
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

redis:
  host: localhost
  port: 6379
  password: pwdpwdpwdpwdpwd